insert into blogs (`title`,`category`,`subCategory`,`content`,`authorId`,`createtime`,`coverUrl`)
 values ('7 CSS tools you should be using ','development','sub_category_id',"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",1,1622649600000,'/assets/images/blog.jpg');
insert into blogs (`title`,`category`,`subCategory`,`content`,`authorId`,`createtime`,`coverUrl`)
 values ('Milan Places That Highlight The City','travel','sub_category_id',"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",2,1654185600000,'/assets/images/blog.jpg');
insert into blogs (`title`,`category`,`subCategory`,`content`,`authorId`,`createtime`,`coverUrl`)
 values ('Online Shopping – An Alternative to Shopping in the Mall','shopping','sub_category_id',"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",2,1658332800000,'/assets/images/blog.jpg');
insert into blogs(`title`,`category`,`subCategory`,`content`,`authorId`,`createtime`,`coverUrl`)
 values ('ADVENTURE IN YOU','adventure','sub_category_id',"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",2,1558195200000,'/assets/images/blog.png');
insert into blogs(`title`,`category`,`subCategory`,`content`,`authorId`,`createtime`,`coverUrl`)
 values ('Loaded BBQ Baked Potatoes','cooking','sub_category_id',"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",1,1521388800000,'/assets/images/blog.jpg');
insert into blogs(`title`,`category`,`subCategory`,`content`,`authorId`,`createtime`,`coverUrl`)
 values ('Beyond the Beach','travel','sub_category_id',"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",1,1269705600000,'/assets/images/blog.jpg');
insert into blogs(`title`,`category`,`subCategory`,`content`,`authorId`,`createtime`,`coverUrl`)
 values ('Art & Perception','art','sub_category_id',"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",2,1871395200000,'/assets/images/blog.jpg');
